### ISSUE TITLE
Bug: Installing thin

### ISSUE THREAD

**Issue by moonglum** [DruRly/gemrat#11]
If you gemrat the thin gem, the following line will be added to your Gemfile:

``` ruby
gem 'thin', '1.5.1, 1.2.11 x86-mingw32 x86-mswin32, 0.7.1 x86-mswin32-60'
```

**Comment by DruRly** [comment]
Thanks. I've been able to replicate this bug. It's an issue. I'll tackle it when I get a chance, if you have any ideas please let me know.

**Comment by moonglum** [comment]
No, I have no idea why this Gem is different, sorry :frowning:

**Comment by DruRly** [comment]
This also occurs when installing `pry` and `puma`.

**Comment by moonglum** [comment]
Awesome :+1:  Thanks :dancer:
