### ISSUE TITLE
Add possibility to specify several gems

### ISSUE THREAD

**Issue by iostaf** [DruRly/gemrat#7]
In case when I need to add several gems I need to do e.g.
gemrat sinatra
gemrat activerecord
I'd like to have option to streamline it just to:
gemrat sinatra activerecord

**Comment by DruRly** [comment]
This is something I've contemplated. May be coming soon. Thanks for raising the issue!

**Comment by shime** [comment]
I'm working on adding more features and this is also one of them, almost done.

**Comment by DruRly** [comment]
Ha! Just spiked out on this a few minutes ago. I'll chill and wait for your pull. Thx @shime!

**Comment by DruRly** [comment]
Multiple gem support has been added to v 0.3.0. Thanks to @shime and others.
